image:
  repository: artifactory.dagility.com/docker/vdchtm-frontend
  tag: latest
  pullPolicy: Always
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx-internal
  hosts:
  - host: vdchtm-frontend-habitat-test3.dagility.com
    paths:
    - /
serviceAccount:
  create: false
